[package]
name = "wasm-browser-extension-test"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "*"

[dependencies.web-sys]
version = "0.3.55"
features = [
    "Window"
]

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
